[2024-04-09T16:50:11.764] [ERROR] error - Error al conectar con la base de datos MongoDB: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
[2024-04-09T18:10:34.994] [ERROR] error - Error al conectar con la base de datos MongoDB: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
[2024-06-13T04:03:15.005] [ERROR] error - StatusError: El correo electrónico ya esta en uso.
    at E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:12:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-13T04:12:23.845] [ERROR] error - StatusError: No se han encontrado el usuario solicitado en la base de datos.
    at E:\nexusforge\api\src\components\users\services\getOneUser.service.ts:10:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\getOneUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-13T04:12:27.319] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at E:\nexusforge\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-13T04:12:38.682] [ERROR] error - CastError: Cast to ObjectId failed for value "38FgipBoG37HmV1FRFi4KOoAlbWkC4eaVi7eQdMEX2XPkpOmxtnvC" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:250:11)
    at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
    at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
    at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
    at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
    at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
    at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
    at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  stringValue: '"38FgipBoG37HmV1FRFi4KOoAlbWkC4eaVi7eQdMEX2XPkpOmxtnvC"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: '38FgipBoG37HmV1FRFi4KOoAlbWkC4eaVi7eQdMEX2XPkpOmxtnvC',
  path: '_id',
  reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
      at new ObjectId (E:\nexusforge\api\node_modules\bson\src\objectid.ts:118:15)
      at castObjectId (E:\nexusforge\api\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:248:12)
      at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
      at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
      at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
      at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
      at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
      at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
      at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80),
  valueType: 'string',
  model: Model { User }
}
[2024-06-13T06:05:18.934] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-13T06:05:23.551] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-13T11:10:26.910] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-19T08:47:46.446] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:48:07.429] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:48:25.992] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:48:50.883] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:05.479] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:18.187] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:33.652] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:36.977] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:37.173] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:37.549] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:55.237] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:49:56.958] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T08:58:00.369] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T09:01:35.842] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T09:14:46.608] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-19T09:57:52.980] [ERROR] error - Error: Invalid login: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-6fee3baa4ffsm9646858a12.80 - gsmtp
    at SMTPConnection._formatError (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:798:19)
    at SMTPConnection._actionAUTHComplete (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:1577:34)
    at SMTPConnection.<anonymous> (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:554:26)
    at SMTPConnection._processResponse (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:982:20)
    at SMTPConnection._onData (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:763:14)
    at TLSSocket.SMTPConnection._onSocketData (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:195:44)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3) {
  code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. For more information, go to\n' +
    '535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-6fee3baa4ffsm9646858a12.80 - gsmtp',
  responseCode: 535,
  command: 'AUTH PLAIN'
}
[2024-06-19T10:08:25.371] [ERROR] error - Error: Invalid login: 534-5.7.9 Application-specific password required. For more information, go to
534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d2e1a72fcca58-705ccb4aa4fsm10599247b3a.131 - gsmtp
    at SMTPConnection._formatError (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:798:19)
    at SMTPConnection._actionAUTHComplete (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:1577:34)
    at SMTPConnection.<anonymous> (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:554:26)
    at SMTPConnection._processResponse (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:982:20)
    at SMTPConnection._onData (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:763:14)
    at TLSSocket.SMTPConnection._onSocketData (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:195:44)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3) {
  code: 'EAUTH',
  response: '534-5.7.9 Application-specific password required. For more information, go to\n' +
    '534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d2e1a72fcca58-705ccb4aa4fsm10599247b3a.131 - gsmtp',
  responseCode: 534,
  command: 'AUTH PLAIN'
}
[2024-06-19T10:09:42.427] [ERROR] error - Error: Invalid login: 534-5.7.9 Application-specific password required. For more information, go to
534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d9443c01a7336-1f855f0c138sm116050755ad.211 - gsmtp
    at SMTPConnection._formatError (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:798:19)
    at SMTPConnection._actionAUTHComplete (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:1577:34)
    at SMTPConnection.<anonymous> (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:554:26)
    at SMTPConnection._processResponse (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:982:20)
    at SMTPConnection._onData (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:763:14)
    at TLSSocket.SMTPConnection._onSocketData (E:\nexusforge\api\node_modules\nodemailer\lib\smtp-connection\index.js:195:44)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3) {
  code: 'EAUTH',
  response: '534-5.7.9 Application-specific password required. For more information, go to\n' +
    '534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d9443c01a7336-1f855f0c138sm116050755ad.211 - gsmtp',
  responseCode: 534,
  command: 'AUTH PLAIN'
}
[2024-06-19T10:51:20.446] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:124:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-19T10:52:52.317] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:126:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:113:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-19T10:53:22.729] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:126:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-19T10:53:40.011] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:126:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-19T10:53:46.350] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:126:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-19T10:54:21.623] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-19T23:46:24.197] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-20T00:03:08.782] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-06-20T00:46:42.002] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-20T00:50:30.075] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-20T00:50:47.667] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:26:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-20T00:51:36.320] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-21T02:51:36.635] [ERROR] error - StatusError: Usuario no encontrado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-06-21T03:13:06.187] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.throw (<anonymous>)
    at rejected (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-21T03:13:08.421] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.throw (<anonymous>)
    at rejected (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-21T03:13:56.329] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.throw (<anonymous>)
    at rejected (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-21T03:14:49.411] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.throw (<anonymous>)
    at rejected (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-21T03:15:13.831] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.throw (<anonymous>)
    at rejected (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-21T03:16:04.191] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.throw (<anonymous>)
    at rejected (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-21T04:32:58.505] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:28:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-21T04:36:41.805] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:28:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-21T04:37:26.772] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:28:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-21T04:38:50.425] [ERROR] error - StatusError: Token inválido o expirado.
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:125:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:4:12)
    at Object.restorePassword (E:\nexusforge\api\src\components\auth\services\restorePassword.service.ts:111:20)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:28:20
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\auth\controllers\restore.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-25T06:12:19.635] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-25T09:22:56.813] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-25T09:40:07.668] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-25T09:40:10.684] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-25T09:40:46.425] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-25T16:34:56.840] [ERROR] error - StatusError: La contraseña no debe ser igual a la anterior
    at E:\nexusforge\api\src\components\users\services\updatePassword.service.ts:27:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\updatePassword.service.ts:5:58) {
  status: 401
}
[2024-06-25T16:35:13.835] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-25T16:35:14.815] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-06-25T16:58:00.449] [ERROR] error - StatusError: El correo electrónico ya está en uso.
    at E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:16:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-25T17:02:27.535] [ERROR] error - StatusError: Campos obligatorios no proporcionados.
    at E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:13:34
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:4:12)
    at Object.createNewUser (E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:12:21)
    at E:\nexusforge\api\src\components\users\controllers\createNewUser.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\createNewUser.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-06-25T17:21:30.028] [ERROR] error - StatusError: No se han encontrado el usuario solicitado en la base de datos.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-25T17:21:53.683] [ERROR] error - StatusError: No se han encontrado el usuario solicitado en la base de datos.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:10:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-25T17:22:14.338] [ERROR] error - StatusError: No se han encontrado el usuario solicitado en la base de datos.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-25T17:22:17.609] [ERROR] error - StatusError: No se han encontrado el usuario solicitado en la base de datos.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-25T17:23:19.294] [ERROR] error - StatusError: Faltan parámetros requeridos: email y motivo_baja
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:16:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-06-25T17:23:54.499] [ERROR] error - StatusError: Faltan parámetros requeridos: email y motivo_baja
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:17:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-06-25T17:24:35.455] [ERROR] error - StatusError: Faltan parámetros requeridos: email y motivo_baja
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:15:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-06-25T17:25:33.504] [ERROR] error - StatusError: El usuario ya se encuentra eliminado.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:13:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-26T12:12:09.469] [ERROR] error - StatusError: El usuario ya se encuentra eliminado.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:13:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-06-26T13:39:42.909] [ERROR] error - CastError: Cast to ObjectId failed for value "edit" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:250:11)
    at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
    at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
    at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
    at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
    at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
    at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
    at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  stringValue: '"edit"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: 'edit',
  path: '_id',
  reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
      at new ObjectId (E:\nexusforge\api\node_modules\bson\src\objectid.ts:118:15)
      at castObjectId (E:\nexusforge\api\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:248:12)
      at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
      at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
      at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
      at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
      at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
      at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
      at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80),
  valueType: 'string',
  model: Model { User }
}
[2024-06-26T15:02:58.024] [ERROR] error - Error: User validation failed: last_name: Cast to Object failed for value "test" (type string) at path "last_name"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    last_name: CastError: Cast to Object failed for value "test" (type string) at path "last_name"
        at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1219:27)
        at model.set [as last_name] (E:\nexusforge\api\node_modules\mongoose\lib\helpers\document\compile.js:189:13)
        at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:28:33
        at Generator.next (<anonymous>)
        at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"test"',
      messageFormat: undefined,
      kind: 'Object',
      value: 'test',
      path: 'last_name',
      reason: undefined,
      valueType: 'string'
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:03:54.692] [ERROR] error - Error: User validation failed: last_name: Cast to Object failed for value "test" (type string) at path "last_name"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    last_name: CastError: Cast to Object failed for value "test" (type string) at path "last_name"
        at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1219:27)
        at model.set [as last_name] (E:\nexusforge\api\node_modules\mongoose\lib\helpers\document\compile.js:189:13)
        at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:28:33
        at Generator.next (<anonymous>)
        at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"test"',
      messageFormat: undefined,
      kind: 'Object',
      value: 'test',
      path: 'last_name',
      reason: undefined,
      valueType: 'string'
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:04:15.998] [ERROR] error - Error: User validation failed: last_name: Cast to Object failed for value "testing" (type string) at path "last_name"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    last_name: CastError: Cast to Object failed for value "testing" (type string) at path "last_name"
        at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1219:27)
        at model.set [as last_name] (E:\nexusforge\api\node_modules\mongoose\lib\helpers\document\compile.js:189:13)
        at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:28:33
        at Generator.next (<anonymous>)
        at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"testing"',
      messageFormat: undefined,
      kind: 'Object',
      value: 'testing',
      path: 'last_name',
      reason: undefined,
      valueType: 'string'
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:04:31.900] [ERROR] error - Error: User validation failed: last_name: Cast to Object failed for value "testing" (type string) at path "last_name"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    last_name: CastError: Cast to Object failed for value "testing" (type string) at path "last_name"
        at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1219:27)
        at model.set [as last_name] (E:\nexusforge\api\node_modules\mongoose\lib\helpers\document\compile.js:189:13)
        at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:28:33
        at Generator.next (<anonymous>)
        at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"testing"',
      messageFormat: undefined,
      kind: 'Object',
      value: 'testing',
      path: 'last_name',
      reason: undefined,
      valueType: 'string'
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:04:33.739] [ERROR] error - Error: User validation failed: last_name: Cast to Object failed for value "testing" (type string) at path "last_name"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    last_name: CastError: Cast to Object failed for value "testing" (type string) at path "last_name"
        at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1219:27)
        at model.set [as last_name] (E:\nexusforge\api\node_modules\mongoose\lib\helpers\document\compile.js:189:13)
        at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:28:33
        at Generator.next (<anonymous>)
        at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      stringValue: '"testing"',
      messageFormat: undefined,
      kind: 'Object',
      value: 'testing',
      path: 'last_name',
      reason: undefined,
      valueType: 'string'
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:05:45.876] [ERROR] error - Error: User validation failed: status: `activo` is not a valid enum value for path `status`.
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    status: ValidatorError: `activo` is not a valid enum value for path `status`.
        at validate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1385:13)
        at SchemaString.SchemaType.doValidate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1369:7)
        at E:\nexusforge\api\node_modules\mongoose\lib\document.js:3038:18
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'status',
      value: 'activo',
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:05:52.249] [ERROR] error - Error: User validation failed: status: `activo` is not a valid enum value for path `status`.
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    status: ValidatorError: `activo` is not a valid enum value for path `status`.
        at validate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1385:13)
        at SchemaString.SchemaType.doValidate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1369:7)
        at E:\nexusforge\api\node_modules\mongoose\lib\document.js:3038:18
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'status',
      value: 'activo',
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:36:46.585] [ERROR] error - TypeError: Cannot set properties of undefined (setting 'address')
    at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:51:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-26T15:37:09.008] [ERROR] error - TypeError: Cannot set properties of undefined (setting 'address')
    at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:51:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-26T15:37:26.097] [ERROR] error - TypeError: Cannot set properties of undefined (setting 'address')
    at E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:51:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\updateOneUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-26T15:42:00.750] [ERROR] error - Error: User validation failed: address.number: Cast to Number failed for value "Casa" (type string) at path "number"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    'address.number': ValidatorError: Cast to Number failed for value "Casa" (type string) at path "number"
        at _init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:789:37)
        at init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:736:5)
        at SingleNested.Document.$__init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:694:3)
        at SingleNested.syncWrapper [as $__init] (E:\nexusforge\api\node_modules\kareem\index.js:331:25)
        at SingleNested.Document.init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:638:8)
        at SingleNested.Document.$init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:654:42)
        at SchemaSubdocument.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\subdocument.js:184:12)
        at _init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:786:35)
        at init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:736:5)
        at model.Document.$__init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:694:3) {
      properties: [Object],
      kind: 'cast',
      path: 'number',
      value: 'Casa',
      reason: [CastError]
    }
  },
  _message: 'User validation failed'
}
[2024-06-26T15:42:02.776] [ERROR] error - Error: User validation failed: address.number: Cast to Number failed for value "Casa" (type string) at path "number"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    'address.number': ValidatorError: Cast to Number failed for value "Casa" (type string) at path "number"
        at _init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:789:37)
        at init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:736:5)
        at SingleNested.Document.$__init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:694:3)
        at SingleNested.syncWrapper [as $__init] (E:\nexusforge\api\node_modules\kareem\index.js:331:25)
        at SingleNested.Document.init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:638:8)
        at SingleNested.Document.$init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:654:42)
        at SchemaSubdocument.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\subdocument.js:184:12)
        at _init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:786:35)
        at init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:736:5)
        at model.Document.$__init (E:\nexusforge\api\node_modules\mongoose\lib\document.js:694:3) {
      properties: [Object],
      kind: 'cast',
      path: 'number',
      value: 'Casa',
      reason: [CastError]
    }
  },
  _message: 'User validation failed'
}
[2024-06-28T17:01:09.834] [ERROR] error - CastError: Cast to ObjectId failed for value "delete666a9c8d2ecfb900a06d699d" (type string) at path "_id" for model "User"
    at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:250:11)
    at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
    at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
    at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
    at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
    at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
    at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
    at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  stringValue: '"delete666a9c8d2ecfb900a06d699d"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: 'delete666a9c8d2ecfb900a06d699d',
  path: '_id',
  reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
      at new ObjectId (E:\nexusforge\api\node_modules\bson\src\objectid.ts:118:15)
      at castObjectId (E:\nexusforge\api\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:248:12)
      at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
      at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
      at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
      at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
      at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
      at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
      at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80),
  valueType: 'string',
  model: Model { User }
}
[2024-07-01T13:37:34.130] [ERROR] error - StatusError: No se han encontrado el usuario solicitado en la base de datos.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-01T13:38:33.154] [ERROR] error - StatusError: Faltan parámetros requeridos: email y motivo_baja
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:17:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-01T13:41:17.648] [ERROR] error - StatusError: Todos los campos son necesarios información necesaria
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:17:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-01T13:41:34.696] [ERROR] error - StatusError: Todos los campos son necesarios información necesaria
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:18:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-01T13:43:19.024] [ERROR] error - StatusError: Todos los campos son necesarios información necesaria
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:15:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-01T13:43:53.542] [ERROR] error - StatusError: Todos los campos son necesarios información necesaria
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:17:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-01T13:44:39.250] [ERROR] error - StatusError: El usuario ya se encuentra eliminado.
    at E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:13:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\softDeleteUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-01T13:45:11.620] [ERROR] error - StatusError: Todos los campos son necesarios información necesaria
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:15:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-03T14:07:03.135] [ERROR] error - Error: El producto no se ha encontrado en la base de datos
    at E:\nexusforge\api\src\components\products\services\updateOneProduct.service.ts:18:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\updateOneProduct.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-07-03T14:38:54.990] [ERROR] error - StatusError: No hay productos próximos a vencer en los próximos 7 días.
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:16:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-03T14:39:32.382] [ERROR] error - Error: Product validation failed: name: `Web Pro Test` is not a valid enum value for path `name`.
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    name: ValidatorError: `Web Pro Test` is not a valid enum value for path `name`.
        at validate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1385:13)
        at SchemaString.SchemaType.doValidate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1369:7)
        at E:\nexusforge\api\node_modules\mongoose\lib\document.js:3038:18
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'name',
      value: 'Web Pro Test',
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'Product validation failed'
}
[2024-07-03T14:40:59.197] [ERROR] error - StatusError: No hay productos próximos a vencer en los próximos 7 días.
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:16:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-03T14:41:35.452] [ERROR] error - StatusError: No hay productos próximos a vencer en los próximos 7 días.
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:16:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-03T14:41:50.242] [ERROR] error - StatusError: No hay productos próximos a vencer en los próximos 7 días.
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:16:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-03T14:43:16.950] [ERROR] error - StatusError: No se encontró el usuario asociado al producto Web Pro
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:34:13
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-07-03T14:43:55.841] [ERROR] error - StatusError: No se encontró el usuario asociado al producto Web Pro
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:35:13
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-07-03T14:45:16.647] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:17:9
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:45:25.342] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:17:9
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:45:35.326] [ERROR] error - Error: Product validation failed: user: Cast to ObjectId failed for value "2024-07-05T23:59:59Z" (type string) at path "user" because of "BSONError"
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    user: CastError: Cast to ObjectId failed for value "2024-07-05T23:59:59Z" (type string) at path "user" because of "BSONError"
        at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:250:11)
        at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
        at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1417:22)
        at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1113:16)
        at model.Document (E:\nexusforge\api\node_modules\mongoose\lib\document.js:166:12)
        at model.Model (E:\nexusforge\api\node_modules\mongoose\lib\model.js:131:12)
        at new model (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4816:15)
        at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:20:22
        at Generator.next (<anonymous>)
        at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71 {
      stringValue: '"2024-07-05T23:59:59Z"',
      messageFormat: undefined,
      kind: 'ObjectId',
      value: '2024-07-05T23:59:59Z',
      path: 'user',
      reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
          at new ObjectId (E:\nexusforge\api\node_modules\bson\src\objectid.ts:118:15)
          at castObjectId (E:\nexusforge\api\node_modules\mongoose\lib\cast\objectid.js:25:12)
          at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:248:12)
          at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
          at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1417:22)
          at model.$set (E:\nexusforge\api\node_modules\mongoose\lib\document.js:1113:16)
          at model.Document (E:\nexusforge\api\node_modules\mongoose\lib\document.js:166:12)
          at model.Model (E:\nexusforge\api\node_modules\mongoose\lib\model.js:131:12)
          at new model (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4816:15)
          at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:20:22,
      valueType: 'string'
    }
  },
  _message: 'Product validation failed'
}
[2024-07-03T14:46:23.825] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:17:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:47:19.276] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:17:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:47:50.344] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:17:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:49:08.697] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:17:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:15:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:51:10.621] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:17:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:51:45.411] [ERROR] error - Error: El id del usuario debe ser válido
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:18:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:11:24)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:14:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-03T14:52:39.808] [ERROR] error - StatusError: No se encontró el usuario asociado al producto Web Pro
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:35:13
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-07-03T14:53:31.458] [ERROR] error - StatusError: No se encontró el usuario asociado al producto Web Pro
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:35:13
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-07-03T14:54:12.227] [ERROR] error - StatusError: No se encontró el usuario asociado al producto Web Pro
    at E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:36:13
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\expirationReminder.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-07-03T19:26:27.447] [ERROR] error - StatusError: El correo electrónico ya está en uso.
    at E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:16:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-04T13:27:20.448] [ERROR] error - StrictPopulateError: Cannot populate path `User` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (E:\nexusforge\api\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at populate (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4450:21)
    at _populate (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4410:5)
    at E:\nexusforge\api\node_modules\mongoose\lib\model.js:4382:5
    at new Promise (<anonymous>)
    at Function.populate (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4381:10)
    at model.Query._find (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2282:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:63) {
  path: 'User'
}
[2024-07-04T13:27:24.935] [ERROR] error - StrictPopulateError: Cannot populate path `User` because it is not in your schema. Set the `strictPopulate` option to false to override.
    at getModelsMapForPopulate (E:\nexusforge\api\node_modules\mongoose\lib\helpers\populate\getModelsMapForPopulate.js:50:12)
    at populate (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4450:21)
    at _populate (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4410:5)
    at E:\nexusforge\api\node_modules\mongoose\lib\model.js:4382:5
    at new Promise (<anonymous>)
    at Function.populate (E:\nexusforge\api\node_modules\mongoose\lib\model.js:4381:10)
    at model.Query._find (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2282:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:63) {
  path: 'User'
}
[2024-07-04T17:04:07.516] [ERROR] error - Error: No se encontró ningún usuario con el email tula@hotmail.com
    at E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:21:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\createNewProduct.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-07-10T17:09:36.333] [ERROR] error - MongoServerError: E11000 duplicate key error collection: test.users index: email_1 dup key: { email: "enzito@gmail.com" }
    at InsertOneOperation.execute (E:\nexusforge\api\node_modules\mongodb\src\operations\insert.ts:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async executeOperation (E:\nexusforge\api\node_modules\mongodb\src\operations\execute_operation.ts:181:12) {
  errorResponse: {
    index: 0,
    code: 11000,
    errmsg: 'E11000 duplicate key error collection: test.users index: email_1 dup key: { email: "enzito@gmail.com" }',
    keyPattern: { email: 1 },
    keyValue: { email: 'enzito@gmail.com' }
  },
  index: 0,
  code: 11000,
  keyPattern: { email: 1 },
  keyValue: { email: 'enzito@gmail.com' },
  [Symbol(errorLabels)]: Set(0) {}
}
[2024-07-10T18:45:35.709] [ERROR] error - StatusError: El correo electrónico ya está en uso.
    at E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:16:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-10T19:33:02.039] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-07-11T17:17:16.212] [ERROR] error - CastError: Cast to ObjectId failed for value "client666a9c8d2ecfb900a06d699d" (type string) at path "_id" for model "Product"
    at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:250:11)
    at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
    at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
    at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
    at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
    at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
    at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
    at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  stringValue: '"client666a9c8d2ecfb900a06d699d"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: 'client666a9c8d2ecfb900a06d699d',
  path: '_id',
  reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
      at new ObjectId (E:\nexusforge\api\node_modules\bson\src\objectid.ts:118:15)
      at castObjectId (E:\nexusforge\api\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:248:12)
      at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
      at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
      at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
      at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
      at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
      at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
      at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80),
  valueType: 'string',
  model: Model { Product }
}
[2024-07-11T17:17:51.739] [ERROR] error - CastError: Cast to ObjectId failed for value "client666a9c8d2ecfb900a06d699d" (type string) at path "_id" for model "Product"
    at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:250:11)
    at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
    at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
    at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
    at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
    at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
    at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
    at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  stringValue: '"client666a9c8d2ecfb900a06d699d"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: 'client666a9c8d2ecfb900a06d699d',
  path: '_id',
  reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
      at new ObjectId (E:\nexusforge\api\node_modules\bson\src\objectid.ts:118:15)
      at castObjectId (E:\nexusforge\api\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at SchemaObjectId.cast (E:\nexusforge\api\node_modules\mongoose\lib\schema\objectId.js:248:12)
      at SchemaObjectId.SchemaType.applySetters (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1236:12)
      at SchemaObjectId.SchemaType.castForQuery (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1653:17)
      at cast (E:\nexusforge\api\node_modules\mongoose\lib\cast.js:375:32)
      at model.Query.Query.cast (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4786:12)
      at model.Query.Query._castConditions (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2199:10)
      at model.Query._findOne (E:\nexusforge\api\node_modules\mongoose\lib\query.js:2513:8)
      at model.Query.exec (E:\nexusforge\api\node_modules\mongoose\lib\query.js:4330:80),
  valueType: 'string',
  model: Model { Product }
}
[2024-07-16T18:08:32.392] [ERROR] error - StatusError: No se han encontrado requests en la base de datos.
    at E:\nexusforge\api\src\components\requests\services\getAllRequests.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\requests\services\getAllRequests.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-16T18:08:38.732] [ERROR] error - StatusError: No se han encontrado requests en la base de datos.
    at E:\nexusforge\api\src\components\requests\services\getAllRequests.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\requests\services\getAllRequests.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-16T18:08:49.763] [ERROR] error - StatusError: No se han encontrado requests en la base de datos.
    at E:\nexusforge\api\src\components\requests\services\getAllRequests.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\requests\services\getAllRequests.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-16T18:10:43.863] [ERROR] error - Error: El campo user es obligatorio
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:11:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:9:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-16T18:11:39.078] [ERROR] error - Error: El campo user es obligatorio
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:12:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:10:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-16T18:11:43.663] [ERROR] error - Error: El campo user tiene que ser un object id
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:16:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:10:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-16T18:17:26.730] [ERROR] error - Error: Request validation failed: product: `Web Ecommerce` is not a valid enum value for path `product`.
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    product: ValidatorError: `Web Ecommerce` is not a valid enum value for path `product`.
        at validate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1385:13)
        at SchemaString.SchemaType.doValidate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1369:7)
        at E:\nexusforge\api\node_modules\mongoose\lib\document.js:3038:18
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'product',
      value: 'Web Ecommerce',
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'Request validation failed'
}
[2024-07-17T15:03:54.591] [ERROR] error - StatusError: El correo electrónico ya está en uso.
    at E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:16:27
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\users\services\createNewUser.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-17T16:20:57.077] [ERROR] error - StatusError: Todos los campos son necesarios información necesaria
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:15:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-17T16:37:21.170] [ERROR] error - Error: El campo user es obligatorio
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:13:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:11:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-17T16:37:41.729] [ERROR] error - Error: El campo user es obligatorio
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:13:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:11:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-17T16:38:19.768] [ERROR] error - Error: El campo user es obligatorio
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:13:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:11:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:15:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-17T16:39:36.408] [ERROR] error - Error: El campo user es obligatorio
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:13:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:11:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:15:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-17T16:41:45.859] [ERROR] error - Error: El campo user tiene que ser un ObjectId válido
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:17:11
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (E:\nexusforge\api\src\components\requests\services\createNewRequest.service.ts:11:24)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:15:33
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>)
[2024-07-17T16:46:52.023] [ERROR] error - Error: Request validation failed: product: `668ee3608c2f27cc821d9aae` is not a valid enum value for path `product`.
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    product: ValidatorError: `668ee3608c2f27cc821d9aae` is not a valid enum value for path `product`.
        at validate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1385:13)
        at SchemaString.SchemaType.doValidate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1369:7)
        at E:\nexusforge\api\node_modules\mongoose\lib\document.js:3038:18
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'product',
      value: '668ee3608c2f27cc821d9aae',
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'Request validation failed'
}
[2024-07-22T16:51:44.498] [ERROR] error - StatusError: Todos los campos son necesarios información necesaria
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:15:13
    at Generator.next (<anonymous>)
    at E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:31:71
    at new Promise (<anonymous>)
    at __awaiter (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:27:12)
    at softDeleteUser (E:\nexusforge\api\src\components\users\controllers\softDeleteUser.controller.ts:11:20)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\nexusforge\api\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\nexusforge\api\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\nexusforge\api\node_modules\express\lib\router\layer.js:95:5) {
  status: 400
}
[2024-07-22T19:40:11.484] [ERROR] error - StatusError: La nueva contraseña no puede ser igual a la contraseña actual
    at E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:32:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:5:58) {
  status: 400
}
[2024-07-22T19:43:00.678] [ERROR] error - StatusError: La nueva contraseña no puede ser igual a la contraseña actual
    at E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:32:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:5:58) {
  status: 400
}
[2024-07-23T00:56:22.907] [ERROR] error - StatusError: La contraseña actual es incorrecta
    at E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:29:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:5:58) {
  status: 400
}
[2024-07-23T00:56:30.943] [ERROR] error - StatusError: La nueva contraseña no puede ser igual a la contraseña actual
    at E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:32:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\changePassword.service.ts:5:58) {
  status: 400
}
[2024-07-23T00:58:13.690] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T00:58:22.870] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T00:58:32.044] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T03:13:15.699] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T20:43:37.427] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T20:45:49.426] [ERROR] error - Error: Request validation failed: product: `Test` is not a valid enum value for path `product`.
    at ValidationError.inspect (E:\nexusforge\api\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
    at Object.format (node:internal/util/inspect:2155:10)
    at basicLayout (E:\nexusforge\api\node_modules\log4js\lib\layouts.js:65:52)
    at app (E:\nexusforge\api\node_modules\log4js\lib\appenders\file.js:98:23)
    at E:\nexusforge\api\node_modules\log4js\lib\log4js.js:43:5
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (E:\nexusforge\api\node_modules\log4js\lib\log4js.js:42:21) {
  errors: {
    product: ValidatorError: `Test` is not a valid enum value for path `product`.
        at validate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1385:13)
        at SchemaString.SchemaType.doValidate (E:\nexusforge\api\node_modules\mongoose\lib\schemaType.js:1369:7)
        at E:\nexusforge\api\node_modules\mongoose\lib\document.js:3038:18
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'product',
      value: 'Test',
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'Request validation failed'
}
[2024-07-23T20:52:56.839] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T20:53:03.528] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T21:00:21.298] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T21:02:38.501] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T21:02:40.245] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T21:02:49.754] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T21:02:50.295] [ERROR] error - StatusError: No se han encontrado productos en la base de datos.
    at E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:9:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProducts.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-07-23T21:13:00.518] [ERROR] error - StatusError: No se han encontrado productos asociados a este usuario.
    at E:\nexusforge\api\src\components\products\services\getAllProductsClient.service.ts:12:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProductsClient.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-07-23T21:13:04.860] [ERROR] error - StatusError: No se han encontrado productos asociados a este usuario.
    at E:\nexusforge\api\src\components\products\services\getAllProductsClient.service.ts:12:11
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\products\services\getAllProductsClient.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
[2024-07-24T01:49:59.520] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-07-24T04:00:42.881] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-07-24T04:00:45.289] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-08-16T08:44:12.473] [ERROR] error - StatusError: Credenciales inválidas.
    at E:\nexusforge\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (E:\nexusforge\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-08-19T09:47:05.183] [ERROR] error - Error al conectar con la base de datos MongoDB: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
[2024-08-19T10:02:37.275] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:02:41.394] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:13:00.427] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:13:01.838] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:20:26.287] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:21:12.935] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:21:34.523] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:21:36.912] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:21:45.890] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:21:47.136] [ERROR] error - StatusError: No se han encontrado usuarios en la base de datos.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:8:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\users\services\getAllUsers.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
[2024-08-19T10:26:55.334] [ERROR] error - StatusError: Para desbloquear todas las funcionalidades además de las incluidas en la demo, contratar el servicio.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:13:19
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:4:12)
    at Object.createNewUser (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:12:21)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:14:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 403
}
[2024-08-19T10:27:03.510] [ERROR] error - StatusError: Credenciales inválidas.
    at D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-08-19T10:27:11.015] [ERROR] error - StatusError: Credenciales inválidas.
    at D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-08-19T10:27:16.153] [ERROR] error - StatusError: Credenciales inválidas.
    at D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:17:31
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:5:58) {
  status: 401
}
[2024-08-19T10:27:21.725] [ERROR] error - StatusError: Credenciales inválidas.
    at D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-08-19T10:27:23.443] [ERROR] error - StatusError: Credenciales inválidas.
    at D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:14:20
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\auth\services\login.service.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 401
}
[2024-08-19T10:28:57.093] [ERROR] error - StatusError: La contraseña actual es incorrecta
    at D:\Proyectos\crm-demo-master\api\src\components\auth\services\changePassword.service.ts:29:11
    at Generator.next (<anonymous>)
    at fulfilled (D:\Proyectos\crm-demo-master\api\src\components\auth\services\changePassword.service.ts:5:58) {
  status: 400
}
[2024-08-19T10:30:09.614] [ERROR] error - StatusError: Para desbloquear todas las funcionalidades además de las incluidas en la demo, contratar el servicio.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:13:19
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:4:12)
    at Object.createNewUser (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:12:21)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:14:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:30:42.462] [ERROR] error - StatusError: Para acceder a todas las funcionalidades avanzadas, así como a características adicionales que no están incluidas en la versión de demostración, es necesario contratar el servicio completo. Si deseas más información sobre las opciones de suscripción y los beneficios incluidos, por favor contáctanos o visita nuestra página de precios.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:13:20
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:4:12)
    at Object.createNewUser (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:12:21)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:14:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:31:05.847] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:13:20
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:4:12)
    at Object.createNewUser (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:12:21)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:14:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:38:17.971] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:13:20
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:4:12)
    at Object.createNewUser (D:\Proyectos\crm-demo-master\api\src\components\users\services\createNewUser.service.ts:12:21)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:14:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\createNewUser.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:38:35.522] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\products\services\createNewProduct.service.ts:13:51
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\products\services\createNewProduct.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\products\services\createNewProduct.service.ts:4:12)
    at Object.createNewProduct (D:\Proyectos\crm-demo-master\api\src\components\products\services\createNewProduct.service.ts:12:24)
    at D:\Proyectos\crm-demo-master\api\src\components\products\controllers\createNewProduct.controller.ts:13:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\products\controllers\createNewProduct.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:38:54.777] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\softDeleteRequest.service.ts:6:17
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\softDeleteRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\requests\services\softDeleteRequest.service.ts:4:12)
    at Object.softDeleteRequest (D:\Proyectos\crm-demo-master\api\src\components\requests\services\softDeleteRequest.service.ts:5:74)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\softDeleteRequest.controller.ts:14:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\softDeleteRequest.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:39:03.640] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:14:19
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:13:24)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:39:08.228] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:14:19
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:13:24)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:39:13.684] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\updateOneUser.service.ts:11:17
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\services\updateOneUser.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\users\services\updateOneUser.service.ts:4:12)
    at Object.updateOneUser (D:\Proyectos\crm-demo-master\api\src\components\users\services\updateOneUser.service.ts:10:21)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\updateOneUser.controller.ts:14:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\users\controllers\updateOneUser.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T10:44:58.228] [ERROR] error - StatusError: Para acceder a todas las funcionalidades y características adicionales, es necesario contratar el servicio completo.
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:14:19
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:4:12)
    at Object.createNewRequest (D:\Proyectos\crm-demo-master\api\src\components\requests\services\createNewRequest.service.ts:13:24)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\createNewRequest.controller.ts:13:33
    at Generator.next (<anonymous>)
    at D:\Proyectos\crm-demo-master\api\src\components\requests\controllers\createNewRequest.controller.ts:31:71
    at new Promise (<anonymous>) {
  status: 400
}
[2024-08-19T11:44:18.421] [ERROR] error - Error en servidor Error: listen EADDRINUSE: address already in use :::8080
[2024-08-19T11:44:18.424] [ERROR] error - Error al conectar con la base de datos MongoDB: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
[2024-08-19T11:47:28.544] [ERROR] error - Error al conectar con la base de datos MongoDB: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
[2024-08-19T11:48:09.465] [ERROR] error - Error al conectar con la base de datos MongoDB: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
[2024-08-19T11:50:16.097] [ERROR] error - Error al conectar con la base de datos MongoDB: MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
